//
//  ArticleViewController.swift
//  News
//
//  Created by Dunja Acimovic on 25.06.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticleViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ArticlePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension ArticleViewController: ArticleViewInterface {
}
