//
//  ArticlePresenter.swift
//  News
//
//  Created by Dunja Acimovic on 25.06.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ArticlePresenter {

    // MARK: - Private properties -

    private unowned let view: ArticleViewInterface
    private let interactor: ArticleInteractorInterface
    private let wireframe: ArticleWireframeInterface

    // MARK: - Lifecycle -

    init(view: ArticleViewInterface, interactor: ArticleInteractorInterface, wireframe: ArticleWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ArticlePresenter: ArticlePresenterInterface {
}
