//
//  ArticleWireframe.swift
//  News
//
//  Created by Dunja Acimovic on 25.06.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticleWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Article", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: ArticleViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = ArticleInteractor()
        let presenter = ArticlePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ArticleWireframe: ArticleWireframeInterface {
}
