//
//  ArticleInterfaces.swift
//  News
//
//  Created by Dunja Acimovic on 25.06.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ArticleWireframeInterface: WireframeInterface {
}

protocol ArticleViewInterface: ViewInterface {
}

protocol ArticlePresenterInterface: PresenterInterface {
}

protocol ArticleInteractorInterface: InteractorInterface {
}
