//
//  NewsInteractor.swift
//  News
//
//  Created by Dunja Acimovic on 30.05.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class NewsInteractor {
}

// MARK: - Extensions -

extension NewsInteractor: NewsInteractorInterface {
    func getTopStories(completion: @escaping (Result<[Article], Error>) -> Void) {
        let topStoriesURLString =  "https://newsapi.org/v2/top-headlines?country=gb&apiKey=150ea451ba96494087d7b02da49a4b4f"
        guard let url = URL(string: topStoriesURLString) else { return }
        let _ = URLSession.shared.dataTask(with: url) { (data, _, error) in
            if let error = error {
                print(error)
                return
            } else if let data = data {
                do {
                    let result = try JSONDecoder().decode(APIResponse.self, from: data)
                    completion(.success(result.articles))
                } catch {
                    completion(.failure(error))
                }
            }
        }.resume()
    }
    
    func getImage(from url: String, completion: @escaping (Result<UIImage?, Error>) -> Void) {
        guard let url = URL(string: url) else { return }
        URLSession.shared.dataTask(with: url) { data, _, error in
            guard let data = data, error == nil else { return }
            DispatchQueue.main.async {
                completion(.success(UIImage(data: data)))
            }
        }.resume()
    }
}
