//
//  NewsInterfaces.swift
//  News
//
//  Created by Dunja Acimovic on 30.05.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum NewsNavigationOption {
    case article(Article)
}

protocol NewsWireframeInterface: WireframeInterface {
    func navigate(to: NewsNavigationOption)
}

protocol NewsViewInterface: ViewInterface {
    func reloadData()
}

protocol NewsPresenterInterface: PresenterInterface {
    func viewDidLoad()
    func numberOfItems() -> Int
    func item(at indexPath: IndexPath) -> NewsViewItemInterface
}

protocol NewsInteractorInterface: InteractorInterface {
    func getTopStories(completion: @escaping (Result<[Article], Error>) -> Void)
    func getImage(from url: String, completion: @escaping (Result<UIImage?, Error>) -> Void)
}

protocol NewsViewItemInterface {
    var title: String? { get }
    var description: String? { get }
    var imageURL: String? { get }
    var imageData: Data? { get set }
}
